# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0

# Orchestrate or schedule a set of jobs
workflows:
  ui:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "circle-latest"
          path: "./soltree-ui/"
          dockerfile: "./Dockerfile"
          filters:
            branches:
              only:
                - main